### ISSUE TITLE
Request to Add a LICENSE File

### ISSUE THREAD

**Issue by Capotasto** [bryceco/OpeningHours#1]
Hello, @bryceco 

I hope this message finds you well. 
I'm looking for the well-maintained OSM opening hours parser libs and I find this repository incredibly useful and well-developed. However,  I noticed that there is currently no LICENSE file in the repository. Having a clear license is beneficial not just for you as the owner, but also for others who use your project. It can protect your rights and set clear guidelines for how others may use, modify, or distribute your work. 

Adding an open-source license like MIT, Apache 2.0, or GPL would be greatly appreciated and would provide clarity for everyone. Thank you for considering this request. I believe that adding a license will help this project continue to grow and benefit the community.

Thank you

**Comment by bryceco** [comment]
I'll add a GPL license in the next week or so.

**Comment by Capotasto** [comment]
Thank you! Appreciate it.

**Comment by Capotasto** [comment]
Hi, @bryceco 

I have encountered a licensing issue with the GPL license, which requires that any derivative work must also be open-sourced under the GPL. This poses a challenge for me because I'm working on an internal application that cannot be open-sourced due to its nature.
 
I understand that changing a project's license is a significant decision, but I kindly request that you consider re-licensing the project under a more permissive license like the MIT or Apache License.

I truly respect the hard work you've put into this project and I will honor your decision, regardless of what it may be. I hope you will consider this request, as the change in licensing would significantly assist my work and potentially that of many others.

Thank you for your time and consideration.

**Comment by bryceco** [comment]
I can use Lesser GPL instead. Do you intend to contribute any code/tests?

**Comment by Capotasto** [comment]
@bryceco 
Thank you very much for your prompt response and for considering my request. I appreciate the change to LGPL, which certainly offers more flexibility than the GPL. However, the project I'm working on is an SDK that gets included into the main executable of applications, and as per my understanding, the LGPL would still require my project to be open-source if it includes your code. Because of the nature of my application, it must remain proprietary. Therefore, I kindly ask if you would reconsider changing the license to an even more permissive one, such as MIT or Apache. 

Thank you again for your consideration.

**Comment by bryceco** [comment]
@Capotasto 
I've added a LGPL license file. You can import the OpeningHours package into your SDK without opening-sourcing your own code. However if you modify the OpeningHours package then you're required to make those changes public, ideally by submitting them as a PR here.

**Comment by Capotasto** [comment]
Thanks, @bryceco. I appreciate it.
